test-1:
	@go test fizzbuzz.go fizzbuzz_test.go -v

test-2:
	@go test tdd -v

test-3:
	@go test -run FizzBuzz -v 

test-coverage:
	@go test -cover -v

test_race:
	@go test -race -v

test-json:
	@go test -json >> test.json